import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedGroupWidget4.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedEllipse6Widget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedEllipse7Widget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedRp7000Widget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedRectangle148Widget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedTantiMawarAndhiniWidget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedEllipse11Widget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedTolongdikemasdenganamanWidget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedLine22Widget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedTotalPembayaranWidget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedRectangle156Widget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedAlfamartWidget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedLine168Widget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedNotebookBajuTartanWidget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedRp29000Widget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedGopayWidget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedNamaLengkapWidget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedIndomaretWidget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedNomorTeleponWidget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedBayarditempatWidget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedEllipse8Widget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedAlamatWidget3.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedRectangle152Widget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedEllipse10Widget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedOvoWidget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedTotalOngkirWidget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedPengirimanWidget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedButtonPesanWidget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedHarga22000Widget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedJlPahlawanNo36NusaBangsaKecMerdekaWidget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedEllipse9Widget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedRectangle170Widget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedDanaWidget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedCatatanWidget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedLine167Widget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/Generated088Widget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedRekeningWidget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedPilihPembayaranWidget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/Generated1xWidget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedDetailPesananWidget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedMenuWidget4.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget/generated/GeneratedProdukyangdibeliWidget.dart';

/* Frame Checkout
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCheckoutWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 717.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 56.0,
                child: GeneratedRectangle148Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 664.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 53.0,
                child: GeneratedRectangle170Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.06666666666666667;

                  final double height =
                      constraints.maxHeight * 0.03748126010016916;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.048,
                        y: constraints.maxHeight * 0.02548725601685762,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedMenuWidget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 18.0,
                top: 157.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 63.0,
                child: GeneratedRectangle152Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 318.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 75.0,
                child: GeneratedRectangle156Widget(),
              ),
              Positioned(
                left: 63.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 18.0,
                child: GeneratedDetailPesananWidget(),
              ),
              Positioned(
                left: 253.0,
                top: 674.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 34.0,
                child: GeneratedButtonPesanWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 79.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 15.0,
                child: GeneratedNamaLengkapWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 134.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 16.0,
                child: GeneratedAlamatWidget3(),
              ),
              Positioned(
                left: 18.0,
                top: 232.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 13.0,
                child: GeneratedNomorTeleponWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 289.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 15.0,
                child: GeneratedProdukyangdibeliWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 406.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 18.0,
                child: GeneratedPengirimanWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 453.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 13.0,
                child: GeneratedPilihPembayaranWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 635.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 16.0,
                child: GeneratedCatatanWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.896;
                  double scaleX = (constraints.maxWidth * percentWidth) / 336.0;

                  double percentHeight = 0.001394700139470014;
                  double scaleY = (constraints.maxHeight * percentHeight) / 1.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.048,
                        translateY: constraints.maxHeight * 0.17573221757322174,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedLine22Widget())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.896;
                  double scaleX = (constraints.maxWidth * percentWidth) / 336.0;

                  double percentHeight = 0.001394700139470014;
                  double scaleY = (constraints.maxHeight * percentHeight) / 1.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.050666666666666665,
                        translateY: constraints.maxHeight * 0.38493723849372385,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedLine167Widget())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.7253333333333334;
                  double scaleX = (constraints.maxWidth * percentWidth) / 272.0;

                  double percentHeight = 0.001394700139470014;
                  double scaleY = (constraints.maxHeight * percentHeight) / 1.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.21866666666666668,
                        translateY: constraints.maxHeight * 0.905160390516039,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedLine168Widget())
                  ]);
                }),
              ),
              Positioned(
                left: 18.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 20.0,
                child: GeneratedTantiMawarAndhiniWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 162.0,
                right: null,
                bottom: null,
                width: 268.0,
                height: 17.0,
                child: GeneratedJlPahlawanNo36NusaBangsaKecMerdekaWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 257.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 20.0,
                child: Generated088Widget(),
              ),
              Positioned(
                left: 55.0,
                top: 478.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 17.0,
                child: GeneratedBayarditempatWidget(),
              ),
              Positioned(
                left: 115.0,
                top: 319.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 20.0,
                child: GeneratedNotebookBajuTartanWidget(),
              ),
              Positioned(
                left: 115.0,
                top: 346.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 20.0,
                child: GeneratedHarga22000Widget(),
              ),
              Positioned(
                left: 115.0,
                top: 372.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 23.0,
                child: Generated1xWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.04533333333333334;

                  final double height =
                      constraints.maxHeight * 0.02548725601685762;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.05333333333333334,
                        y: constraints.maxHeight * 0.6652719665271967,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 20.0,
                top: 499.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 17.0,
                child: GeneratedEllipse6Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 521.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 17.0,
                child: GeneratedEllipse7Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 543.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 17.0,
                child: GeneratedEllipse8Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 565.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 17.0,
                child: GeneratedEllipse9Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 587.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 17.0,
                child: GeneratedEllipse10Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 607.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 17.0,
                child: GeneratedEllipse11Widget(),
              ),
              Positioned(
                left: 55.0,
                top: 501.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 20.0,
                child: GeneratedRekeningWidget(),
              ),
              Positioned(
                left: 55.0,
                top: 523.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 20.0,
                child: GeneratedIndomaretWidget(),
              ),
              Positioned(
                left: 55.0,
                top: 544.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 20.0,
                child: GeneratedAlfamartWidget(),
              ),
              Positioned(
                left: 55.0,
                top: 565.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 20.0,
                child: GeneratedOvoWidget(),
              ),
              Positioned(
                left: 55.0,
                top: 587.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 20.0,
                child: GeneratedDanaWidget(),
              ),
              Positioned(
                left: 55.0,
                top: 608.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 20.0,
                child: GeneratedGopayWidget(),
              ),
              Positioned(
                left: 88.0,
                top: 633.0,
                right: null,
                bottom: null,
                width: 174.0,
                height: 17.0,
                child: GeneratedTolongdikemasdenganamanWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 431.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 17.0,
                child: GeneratedTotalOngkirWidget(),
              ),
              Positioned(
                left: 95.0,
                top: 428.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 20.0,
                child: GeneratedRp7000Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 671.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 20.0,
                child: GeneratedTotalPembayaranWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 690.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 23.0,
                child: GeneratedRp29000Widget(),
              )
            ]),
      ),
    ));
  }
}
