import 'package:flutter/material.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedNotebookRollerPolozWidget1.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedAddBasketWidget20.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedAddBasketWidget21.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedRp16000Widget4.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedRp19000Widget2.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedAddBasketWidget23.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedNotebookPunyaTaliWidget1.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedFotoProdukWidget13.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedFotoProdukWidget18.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedMenuWidget16.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedButtonBeliWidget23.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedButtonBeliWidget18.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedFotoProdukWidget12.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedButtonBeliWidget19.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedRp22000Widget2.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedAddBasketWidget17.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedNotebookBajuBiruWidget1.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedButtonBeliWidget21.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedRp18000Widget3.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedNotebookMemakaiBajuBulpenWidget1.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedButtonBeliWidget20.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedNotebookRollerCanteqWidget2.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedRp12000Widget1.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedRp11000Widget1.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedNotebookBajuTartanWidget5.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedFotoProdukWidget14.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedButtonBeliWidget17.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedAddBasketWidget19.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedFotoProdukWidget17.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedAddBasketWidget18.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedButtonBeliWidget22.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedFotoProdukWidget15.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedFotoProdukWidget16.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedAddBasketWidget22.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedRp20000Widget2.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget1/generated/GeneratedNotebookRollerBinderWidget2.dart';

/* Frame Laman Hasil Pencarian
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLamanHasilPencarianWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1123.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1123.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2853333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0943900267141585;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.07466666666666667,
                                      y: constraints.maxHeight *
                                          0.08281389136242208,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedFotoProdukWidget12(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2853333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0943900267141585;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.07466666666666667,
                                      y: constraints.maxHeight *
                                          0.21104185218165628,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedFotoProdukWidget13(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2853333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0943900267141585;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.07733333333333334,
                                      y: constraints.maxHeight *
                                          0.3428317008014248,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedFotoProdukWidget14(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2853333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0943900267141585;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.07733333333333334,
                                      y: constraints.maxHeight *
                                          0.4764024933214604,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedFotoProdukWidget15(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2853333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0943900267141585;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.07466666666666667,
                                      y: constraints.maxHeight *
                                          0.6090828138913624,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedFotoProdukWidget16(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2853333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0943900267141585;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.08533333333333333,
                                      y: constraints.maxHeight *
                                          0.7417631344612645,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedFotoProdukWidget17(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2853333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0943900267141585;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.096,
                                      y: constraints.maxHeight *
                                          0.8744434550311665,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedFotoProdukWidget18(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 28.0,
                              top: 28.0,
                              right: null,
                              bottom: null,
                              width: 25.0,
                              height: 25.0,
                              child: GeneratedMenuWidget16(),
                            ),
                            Positioned(
                              left: 203.0,
                              top: 173.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 27.0,
                              child: GeneratedButtonBeliWidget17(),
                            ),
                            Positioned(
                              left: 203.0,
                              top: 320.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 27.0,
                              child: GeneratedButtonBeliWidget18(),
                            ),
                            Positioned(
                              left: 203.0,
                              top: 464.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 27.0,
                              child: GeneratedButtonBeliWidget19(),
                            ),
                            Positioned(
                              left: 203.0,
                              top: 614.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 27.0,
                              child: GeneratedButtonBeliWidget20(),
                            ),
                            Positioned(
                              left: 203.0,
                              top: 763.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 27.0,
                              child: GeneratedButtonBeliWidget21(),
                            ),
                            Positioned(
                              left: 203.0,
                              top: 912.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 27.0,
                              child: GeneratedButtonBeliWidget22(),
                            ),
                            Positioned(
                              left: 203.0,
                              top: 1057.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 27.0,
                              child: GeneratedButtonBeliWidget23(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 94.0,
                              right: null,
                              bottom: null,
                              width: 151.0,
                              height: 21.0,
                              child: GeneratedNotebookRollerCanteqWidget2(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 125.0,
                              right: null,
                              bottom: null,
                              width: 75.0,
                              height: 19.0,
                              child: GeneratedRp16000Widget4(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 268.0,
                              right: null,
                              bottom: null,
                              width: 75.0,
                              height: 19.0,
                              child: GeneratedRp18000Widget3(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 416.0,
                              right: null,
                              bottom: null,
                              width: 75.0,
                              height: 19.0,
                              child: GeneratedRp12000Widget1(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 566.0,
                              right: null,
                              bottom: null,
                              width: 75.0,
                              height: 19.0,
                              child: GeneratedRp19000Widget2(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 728.0,
                              right: null,
                              bottom: null,
                              width: 75.0,
                              height: 19.0,
                              child: GeneratedRp20000Widget2(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 871.0,
                              right: null,
                              bottom: null,
                              width: 75.0,
                              height: 19.0,
                              child: GeneratedRp22000Widget2(),
                            ),
                            Positioned(
                              left: 162.0,
                              top: 1013.0,
                              right: null,
                              bottom: null,
                              width: 75.0,
                              height: 19.0,
                              child: GeneratedRp11000Widget1(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 239.0,
                              right: null,
                              bottom: null,
                              width: 128.0,
                              height: 20.0,
                              child: GeneratedNotebookPunyaTaliWidget1(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 385.0,
                              right: null,
                              bottom: null,
                              width: 133.0,
                              height: 20.0,
                              child: GeneratedNotebookRollerPolozWidget1(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 535.0,
                              right: null,
                              bottom: null,
                              width: 141.0,
                              height: 20.0,
                              child: GeneratedNotebookRollerBinderWidget2(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 684.0,
                              right: null,
                              bottom: null,
                              width: 129.0,
                              height: 38.0,
                              child:
                                  GeneratedNotebookMemakaiBajuBulpenWidget1(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 833.0,
                              right: null,
                              bottom: null,
                              width: 144.0,
                              height: 20.0,
                              child: GeneratedNotebookBajuTartanWidget5(),
                            ),
                            Positioned(
                              left: 162.0,
                              top: 983.0,
                              right: null,
                              bottom: null,
                              width: 144.0,
                              height: 20.0,
                              child: GeneratedNotebookBajuBiruWidget1(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 173.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedAddBasketWidget17(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 320.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedAddBasketWidget18(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 464.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedAddBasketWidget19(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 614.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedAddBasketWidget20(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 763.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedAddBasketWidget21(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 912.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedAddBasketWidget22(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 1057.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedAddBasketWidget23(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
