import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/atsapp/generatedmenuwidget14/generated/GeneratedButtonPesananWidget1.dart';
import 'package:flutterapp/atsapp/generatedmenuwidget14/generated/GeneratedButtonKeranjangWidget1.dart';
import 'package:flutterapp/atsapp/generatedmenuwidget14/generated/GeneratedMenuWidget15.dart';
import 'package:flutterapp/atsapp/generatedmenuwidget14/generated/GeneratedStationaryBookWidget1.dart';
import 'package:flutterapp/atsapp/generatedmenuwidget14/generated/GeneratedButtonJelajahWidget.dart';
import 'package:flutterapp/atsapp/generatedmenuwidget14/generated/GeneratedButtonProfilWidget.dart';
import 'package:flutterapp/atsapp/generatedmenuwidget14/generated/GeneratedButtonBerandaWidget.dart';

/* Frame Menu
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMenuWidget14 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.only(
        topLeft: Radius.circular(0.0),
        topRight: Radius.circular(11.0),
        bottomRight: Radius.circular(11.0),
        bottomLeft: Radius.circular(0.0),
      ),
      child: Container(
        width: 309.0,
        height: 667.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.only(
            topLeft: Radius.circular(0.0),
            topRight: Radius.circular(11.0),
            bottomRight: Radius.circular(11.0),
            bottomLeft: Radius.circular(0.0),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(0.0),
                  topRight: Radius.circular(11.0),
                  bottomRight: Radius.circular(11.0),
                  bottomLeft: Radius.circular(0.0),
                ),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.08090614886731391;

                  final double height =
                      constraints.maxHeight * 0.037481259370314844;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.08090614886731391,
                        y: constraints.maxHeight * 0.034482758620689655,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedMenuWidget15(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.48220064724919093;

                  final double height =
                      constraints.maxHeight * 0.04047976011994003;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.45307443365695793,
                        y: constraints.maxHeight * 0.034482758620689655,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedStationaryBookWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8349765419574231;

                  final double height =
                      constraints.maxHeight * 0.043478260869565216;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.08090614886731391,
                        y: constraints.maxHeight * 0.12443778110944528,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedButtonBerandaWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8349765419574231;

                  final double height =
                      constraints.maxHeight * 0.037481259370314844;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.08090614886731391,
                        y: constraints.maxHeight * 0.21139430284857572,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedButtonJelajahWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8349765419574231;

                  final double height =
                      constraints.maxHeight * 0.04047976011994003;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.08090614886731391,
                        y: constraints.maxHeight * 0.28785607196401797,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedButtonKeranjangWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8349765419574231;

                  final double height =
                      constraints.maxHeight * 0.04047976011994003;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.08090614886731391,
                        y: constraints.maxHeight * 0.3613193403298351,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedButtonPesananWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8349765419574231;

                  final double height =
                      constraints.maxHeight * 0.034482758620689655;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.08090614886731391,
                        y: constraints.maxHeight * 0.44227886056971516,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedButtonProfilWidget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
