import 'package:flutter/material.dart';

/* Rectangle Close
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCloseWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 18.0,
      height: 18.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/6d2ac1e128ddba59f12888969b08fd1e7789464a.png",
          color: null,
          fit: BoxFit.contain,
          width: 18.0,
          height: 18.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
