import 'package:flutter/material.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedRectangle189Widget3.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedRectangle180Widget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedRectangle135Widget6.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedLine210Widget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedLine204Widget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedRectangle185Widget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedRating_BintangWidget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedLine212Widget2.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedLine91Widget3.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedLine209Widget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedRectangle182Widget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedRectangle187Widget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedUbahWidget1.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedRectangle184Widget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedLine205Widget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedRectangle135Widget7.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedRectangle183Widget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedRectangle135Widget4.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedRectangle186Widget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedDetailProdukWidget5.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedLine207Widget1.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedLine213Widget2.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedLine208Widget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedLine206Widget2.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedNamaProdukWidget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedLine203Widget2.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedLine211Widget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedHapusWidget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedMenulogoWidget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedRectangle188Widget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedRincianProdukWidget2.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget4/generated/GeneratedRectangle178Widget2.dart';

/* Frame Detail Produk
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDetailProdukWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 57.0,
                child: GeneratedRectangle178Widget2(),
              ),
              Positioned(
                left: 14.0,
                top: 12.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 34.0,
                child: GeneratedMenulogoWidget(),
              ),
              Positioned(
                left: 49.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 169.0,
                height: 28.0,
                child: GeneratedDetailProdukWidget5(),
              ),
              Positioned(
                left: 57.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 261.0,
                height: 249.0,
                child: GeneratedRectangle135Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 312.0,
                right: null,
                bottom: null,
                width: 375.0013427734375,
                height: 1.0,
                child: GeneratedLine203Widget2(),
              ),
              Positioned(
                left: 57.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 360.7242431640625,
                height: 1.0,
                child: GeneratedLine204Widget(),
              ),
              Positioned(
                left: 316.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 358.5874938964844,
                height: 1.0,
                child: GeneratedLine205Widget(),
              ),
              Positioned(
                left: 26.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 275.0,
                height: 44.0,
                child: GeneratedNamaProdukWidget(),
              ),
              Positioned(
                left: 26.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 18.0,
                child: GeneratedRating_BintangWidget(),
              ),
              Positioned(
                left: 157.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 1.0,
                child: GeneratedLine206Widget2(),
              ),
              Positioned(
                left: 261.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 1.0,
                child: GeneratedLine207Widget1(),
              ),
              Positioned(
                left: 131.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 17.0,
                child: GeneratedRectangle180Widget(),
              ),
              Positioned(
                left: 275.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 17.0,
                child: GeneratedRectangle183Widget(),
              ),
              Positioned(
                left: 306.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 17.0,
                child: GeneratedRectangle184Widget(),
              ),
              Positioned(
                left: 170.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 17.0,
                child: GeneratedRectangle182Widget(),
              ),
              Positioned(
                left: 275.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 26.248809814453125,
                height: 1.0,
                child: GeneratedLine208Widget(),
              ),
              Positioned(
                left: 295.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 25.612497329711914,
                height: 1.0,
                child: GeneratedLine209Widget(),
              ),
              Positioned(
                left: 306.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 24.83948516845703,
                height: 1.0,
                child: GeneratedLine210Widget(),
              ),
              Positioned(
                left: 326.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 25.612497329711914,
                height: 1.0,
                child: GeneratedLine211Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 409.0458984375,
                right: null,
                bottom: null,
                width: 374.9998779296875,
                height: 1.0,
                child: GeneratedLine91Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 454.0458984375,
                right: null,
                bottom: null,
                width: 374.9998779296875,
                height: 1.0,
                child: GeneratedLine212Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 617.0458984375,
                right: null,
                bottom: null,
                width: 374.9998779296875,
                height: 1.0,
                child: GeneratedLine213Widget2(),
              ),
              Positioned(
                left: 25.0,
                top: 422.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 21.0,
                child: GeneratedRincianProdukWidget2(),
              ),
              Positioned(
                left: 25.0,
                top: 467.0,
                right: null,
                bottom: null,
                width: 247.0,
                height: 17.0,
                child: GeneratedRectangle135Widget6(),
              ),
              Positioned(
                left: 25.0,
                top: 494.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 17.0,
                child: GeneratedRectangle185Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 521.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 17.0,
                child: GeneratedRectangle186Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 548.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 17.0,
                child: GeneratedRectangle187Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 573.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 17.0,
                child: GeneratedRectangle188Widget(),
              ),
              Positioned(
                left: 53.0,
                top: 622.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 36.0,
                child: GeneratedRectangle135Widget7(),
              ),
              Positioned(
                left: 211.0,
                top: 622.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 36.0,
                child: GeneratedRectangle189Widget3(),
              ),
              Positioned(
                left: 233.0,
                top: 633.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 19.0,
                child: GeneratedUbahWidget1(),
              ),
              Positioned(
                left: 75.0,
                top: 632.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 19.0,
                child: GeneratedHapusWidget(),
              )
            ]),
      ),
    ));
  }
}
