import 'package:flutter/material.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget4/generated/GeneratedButtonKategoriNotebookWidget1.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget4/generated/GeneratedButtonKategoriBukuWidget1.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget4/generated/GeneratedButtonOrigamiWidget1.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget4/generated/GeneratedButtonKategoriBulpenWidget1.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget4/generated/GeneratedButtonKategoriMapBerkasWidget1.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget4/generated/GeneratedButtonSearchWidget12.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget4/generated/GeneratedButtonKategoriPenghapusWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget4/generated/GeneratedJelajahWidget5.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget4/generated/GeneratedButtonKategoriAlatLukisWidget1.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget4/generated/GeneratedButtonKategoriBusurJangkaWidget1.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget4/generated/GeneratedButtonKategoriPenggarisWidget1.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget4/generated/GeneratedButtonKategoriPensilWidget1.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget4/generated/GeneratedMenuWidget17.dart';

/* Frame Jelajah
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedJelajahWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(63, 0, 0, 0),
            offset: Offset(0.0, 4.0),
            blurRadius: 4.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 667.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 26.0,
                  top: 66.0,
                  right: null,
                  bottom: null,
                  width: 152.0,
                  height: 49.0,
                  child: GeneratedJelajahWidget5(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.06666666666666667;

                    final double height =
                        constraints.maxHeight * 0.037481259370314844;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.06933333333333333,
                          y: constraints.maxHeight * 0.041979010494752625,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedMenuWidget17(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 26.0,
                  top: 204.0,
                  right: null,
                  bottom: null,
                  width: 80.0,
                  height: 80.0,
                  child: GeneratedButtonKategoriBukuWidget1(),
                ),
                Positioned(
                  left: 143.0,
                  top: 204.0,
                  right: null,
                  bottom: null,
                  width: 80.0,
                  height: 80.0,
                  child: GeneratedButtonKategoriPensilWidget1(),
                ),
                Positioned(
                  left: 264.0,
                  top: 204.0,
                  right: null,
                  bottom: null,
                  width: 80.0,
                  height: 80.0,
                  child: GeneratedButtonKategoriPenghapusWidget1(),
                ),
                Positioned(
                  left: 26.0,
                  top: 320.0,
                  right: null,
                  bottom: null,
                  width: 80.0,
                  height: 80.0,
                  child: GeneratedButtonKategoriBulpenWidget1(),
                ),
                Positioned(
                  left: 26.0,
                  top: 436.0,
                  right: null,
                  bottom: null,
                  width: 80.0,
                  height: 80.0,
                  child: GeneratedButtonKategoriNotebookWidget1(),
                ),
                Positioned(
                  left: 143.0,
                  top: 552.0,
                  right: null,
                  bottom: null,
                  width: 80.0,
                  height: 80.0,
                  child: GeneratedButtonOrigamiWidget1(),
                ),
                Positioned(
                  left: 264.0,
                  top: 436.0,
                  right: null,
                  bottom: null,
                  width: 80.0,
                  height: 80.0,
                  child: GeneratedButtonKategoriMapBerkasWidget1(),
                ),
                Positioned(
                  left: 143.0,
                  top: 436.0,
                  right: null,
                  bottom: null,
                  width: 80.0,
                  height: 80.0,
                  child: GeneratedButtonKategoriBusurJangkaWidget1(),
                ),
                Positioned(
                  left: 143.0,
                  top: 320.0,
                  right: null,
                  bottom: null,
                  width: 80.0,
                  height: 80.0,
                  child: GeneratedButtonKategoriPenggarisWidget1(),
                ),
                Positioned(
                  left: 264.0,
                  top: 320.0,
                  right: null,
                  bottom: null,
                  width: 80.0,
                  height: 80.0,
                  child: GeneratedButtonKategoriAlatLukisWidget1(),
                ),
                Positioned(
                  left: 53.0,
                  top: 123.0,
                  right: null,
                  bottom: null,
                  width: 268.0,
                  height: 35.0,
                  child: GeneratedButtonSearchWidget12(),
                )
              ]),
        ),
      ),
    ));
  }
}
