import 'package:flutter/material.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget1/generated/GeneratedRectangle156Widget1.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget1/generated/GeneratedNamaLengkapWidget1.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget1/generated/GeneratedTolongdikemasdenganamanWidget1.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget1/generated/GeneratedMenuWidget5.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget1/generated/GeneratedRectangle171Widget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget1/generated/GeneratedRp20000Widget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget1/generated/GeneratedPengirimanWidget1.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget1/generated/GeneratedPembayaranyangdipilihWidget.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget1/generated/GeneratedProdukyangdibeliWidget1.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget1/generated/Generated088Widget1.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget1/generated/GeneratedBayarditempatWidget1.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget1/generated/GeneratedHarga22000Widget1.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget1/generated/GeneratedDetailPesananWidget1.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget1/generated/GeneratedRectangle148Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget1/generated/GeneratedJlPahlawanNo36NusaBangsaKecMerdekaWidget1.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget1/generated/GeneratedNomorTeleponWidget1.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget1/generated/GeneratedRp7000Widget1.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget1/generated/GeneratedTantiMawarAndhiniWidget1.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget1/generated/Generated1xWidget1.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget1/generated/GeneratedButtonPesanWidget1.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget1/generated/GeneratedTotalOngkirWidget1.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget1/generated/GeneratedTotalPembayaranWidget1.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget1/generated/GeneratedAlamatWidget4.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget1/generated/GeneratedCatatanWidget1.dart';
import 'package:flutterapp/atsapp/generatedcheckoutwidget1/generated/GeneratedNotebookBajuTartanWidget1.dart';

/* Frame Checkout
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCheckoutWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 56.0,
                child: GeneratedRectangle148Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.06666666666666667;

                  final double height =
                      constraints.maxHeight * 0.037481259370314844;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.048,
                        y: constraints.maxHeight * 0.025487256371814093,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedMenuWidget5(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 18.0,
                top: 288.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 75.0,
                child: GeneratedRectangle156Widget1(),
              ),
              Positioned(
                left: 63.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 18.0,
                child: GeneratedDetailPesananWidget1(),
              ),
              Positioned(
                left: 18.0,
                top: 79.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 15.0,
                child: GeneratedNamaLengkapWidget1(),
              ),
              Positioned(
                left: 18.0,
                top: 134.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 16.0,
                child: GeneratedAlamatWidget4(),
              ),
              Positioned(
                left: 18.0,
                top: 209.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 13.0,
                child: GeneratedNomorTeleponWidget1(),
              ),
              Positioned(
                left: 18.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 15.0,
                child: GeneratedProdukyangdibeliWidget1(),
              ),
              Positioned(
                left: 18.0,
                top: 386.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 18.0,
                child: GeneratedPengirimanWidget1(),
              ),
              Positioned(
                left: 18.0,
                top: 437.0,
                right: null,
                bottom: null,
                width: 185.0,
                height: 13.0,
                child: GeneratedPembayaranyangdipilihWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 489.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 16.0,
                child: GeneratedCatatanWidget1(),
              ),
              Positioned(
                left: 18.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 20.0,
                child: GeneratedTantiMawarAndhiniWidget1(),
              ),
              Positioned(
                left: 18.0,
                top: 159.0,
                right: null,
                bottom: null,
                width: 267.0,
                height: 38.0,
                child: GeneratedJlPahlawanNo36NusaBangsaKecMerdekaWidget1(),
              ),
              Positioned(
                left: 18.0,
                top: 233.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 23.0,
                child: Generated088Widget1(),
              ),
              Positioned(
                left: 18.0,
                top: 462.0,
                right: null,
                bottom: null,
                width: 97.0,
                height: 20.0,
                child: GeneratedBayarditempatWidget1(),
              ),
              Positioned(
                left: 115.0,
                top: 291.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 20.0,
                child: GeneratedNotebookBajuTartanWidget1(),
              ),
              Positioned(
                left: 115.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 20.0,
                child: GeneratedHarga22000Widget1(),
              ),
              Positioned(
                left: 115.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 23.0,
                child: Generated1xWidget1(),
              ),
              Positioned(
                left: 18.0,
                top: 513.0,
                right: null,
                bottom: null,
                width: 208.0,
                height: 20.0,
                child: GeneratedTolongdikemasdenganamanWidget1(),
              ),
              Positioned(
                left: 18.0,
                top: 412.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 17.0,
                child: GeneratedTotalOngkirWidget1(),
              ),
              Positioned(
                left: 95.0,
                top: 411.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 20.0,
                child: GeneratedRp7000Widget1(),
              ),
              Positioned(
                left: 18.0,
                top: 565.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 23.0,
                child: GeneratedRp20000Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 541.0,
                right: null,
                bottom: null,
                width: 131.0,
                height: 13.0,
                child: GeneratedTotalPembayaranWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 614.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 53.0,
                child: GeneratedRectangle171Widget(),
              ),
              Positioned(
                left: 251.0,
                top: 623.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 36.0,
                child: GeneratedButtonPesanWidget1(),
              )
            ]),
      ),
    ));
  }
}
