import 'package:flutter/material.dart';
import 'package:flutterapp/atsapp/generatedberandawidget6/generated/GeneratedBannerWidget4.dart';
import 'package:flutterapp/atsapp/generatedberandawidget6/generated/GeneratedButtonBeliWidget27.dart';
import 'package:flutterapp/atsapp/generatedberandawidget6/generated/GeneratedDiskon50BacktoSchoolWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/atsapp/generatedberandawidget6/generated/GeneratedTrendingWidget2.dart';
import 'package:flutterapp/atsapp/generatedberandawidget6/generated/GeneratedPensilset7pcsWidget2.dart';
import 'package:flutterapp/atsapp/generatedberandawidget6/generated/GeneratedRp45000Widget2.dart';
import 'package:flutterapp/atsapp/generatedberandawidget6/generated/GeneratedButtonBeliWidget26.dart';
import 'package:flutterapp/atsapp/generatedberandawidget6/generated/GeneratedNotebookSummerBreezeWidget2.dart';
import 'package:flutterapp/atsapp/generatedberandawidget6/generated/GeneratedDiskon30untuksemuaproduklohWidget2.dart';
import 'package:flutterapp/atsapp/generatedberandawidget6/generated/GeneratedBrushpen1Set10pcsWidget2.dart';
import 'package:flutterapp/atsapp/generatedberandawidget6/generated/GeneratedButtonSearchWidget18.dart';
import 'package:flutterapp/atsapp/generatedberandawidget6/generated/GeneratedButtonBeliWidget24.dart';
import 'package:flutterapp/atsapp/generatedberandawidget6/generated/GeneratedFotoProduk3Widget2.dart';
import 'package:flutterapp/atsapp/generatedberandawidget6/generated/GeneratedKalkulatorAjaibMatematikaWidget2.dart';
import 'package:flutterapp/atsapp/generatedberandawidget6/generated/Generated1SetALatLukisLengkapWidget2.dart';
import 'package:flutterapp/atsapp/generatedberandawidget6/generated/GeneratedButtonBeliWidget25.dart';
import 'package:flutterapp/atsapp/generatedberandawidget6/generated/GeneratedFotoProduk4Widget2.dart';
import 'package:flutterapp/atsapp/generatedberandawidget6/generated/GeneratedFotoProduk2Widget2.dart';
import 'package:flutterapp/atsapp/generatedberandawidget6/generated/GeneratedBannerWidget5.dart';
import 'package:flutterapp/atsapp/generatedberandawidget6/generated/GeneratedFotoProdukWidget20.dart';
import 'package:flutterapp/atsapp/generatedberandawidget6/generated/GeneratedRp13000Widget3.dart';
import 'package:flutterapp/atsapp/generatedberandawidget6/generated/GeneratedRp16000Widget5.dart';
import 'package:flutterapp/atsapp/generatedberandawidget6/generated/GeneratedRp18000Widget4.dart';
import 'package:flutterapp/atsapp/generatedberandawidget6/generated/GeneratedBerandaWidget7.dart';
import 'package:flutterapp/atsapp/generatedberandawidget6/generated/GeneratedButtonBeliWidget28.dart';
import 'package:flutterapp/atsapp/generatedberandawidget6/generated/GeneratedRp14000Widget2.dart';
import 'package:flutterapp/atsapp/generatedberandawidget6/generated/GeneratedFotoProduk5Widget2.dart';

/* Frame Beranda
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBerandaWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1123.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1123.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 26.0,
                              top: 56.0,
                              right: null,
                              bottom: null,
                              width: 148.0,
                              height: 36.0,
                              child: GeneratedBerandaWidget7(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 97.0,
                              right: null,
                              bottom: null,
                              width: 135.0,
                              height: 190.00001525878906,
                              child: GeneratedBannerWidget4(),
                            ),
                            Positioned(
                              left: 203.0,
                              top: 97.0,
                              right: null,
                              bottom: null,
                              width: 135.0,
                              height: 190.0,
                              child: GeneratedBannerWidget5(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2853333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0943900267141585;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.377560106856634,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedFotoProdukWidget20(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2853333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0943900267141585;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.5004452359750667,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedFotoProduk2Widget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2853333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0943900267141585;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.6233303650934996,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedFotoProduk3Widget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2853333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0943900267141585;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.7462154942119323,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedFotoProduk4Widget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2853333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0943900267141585;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.8691006233303651,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedFotoProduk5Widget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 26.0,
                              top: 382.0,
                              right: null,
                              bottom: null,
                              width: 128.0,
                              height: 30.0,
                              child: GeneratedTrendingWidget2(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 305.0,
                              right: null,
                              bottom: null,
                              width: 142.0,
                              height: 46.0,
                              child:
                                  GeneratedDiskon30untuksemuaproduklohWidget2(),
                            ),
                            Positioned(
                              left: 203.0,
                              top: 305.0,
                              right: null,
                              bottom: null,
                              width: 101.0,
                              height: 42.0,
                              child: GeneratedDiskon50BacktoSchoolWidget2(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 426.0,
                              right: null,
                              bottom: null,
                              width: 191.0,
                              height: 14.0,
                              child: GeneratedNotebookSummerBreezeWidget2(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 458.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 21.0,
                              child: GeneratedRp16000Widget5(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 593.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 21.0,
                              child: GeneratedRp45000Widget2(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 727.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 21.0,
                              child: GeneratedRp13000Widget3(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 870.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 21.0,
                              child: GeneratedRp14000Widget2(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 1008.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 21.0,
                              child: GeneratedRp18000Widget4(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 562.0,
                              right: null,
                              bottom: null,
                              width: 162.0,
                              height: 22.0,
                              child: Generated1SetALatLukisLengkapWidget2(),
                            ),
                            Positioned(
                              left: 200.0,
                              top: 503.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 27.0,
                              child: GeneratedButtonBeliWidget24(),
                            ),
                            Positioned(
                              left: 200.0,
                              top: 645.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 27.0,
                              child: GeneratedButtonBeliWidget25(),
                            ),
                            Positioned(
                              left: 200.0,
                              top: 779.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 27.0,
                              child: GeneratedButtonBeliWidget26(),
                            ),
                            Positioned(
                              left: 200.0,
                              top: 915.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 27.0,
                              child: GeneratedButtonBeliWidget27(),
                            ),
                            Positioned(
                              left: 200.0,
                              top: 1055.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 27.0,
                              child: GeneratedButtonBeliWidget28(),
                            ),
                            Positioned(
                              left: 154.0,
                              top: 699.0,
                              right: null,
                              bottom: null,
                              width: 145.0,
                              height: 23.0,
                              child: GeneratedBrushpen1Set10pcsWidget2(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 840.0,
                              right: null,
                              bottom: null,
                              width: 109.0,
                              height: 20.0,
                              child: GeneratedPensilset7pcsWidget2(),
                            ),
                            Positioned(
                              left: 156.0,
                              top: 978.0,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 20.0,
                              child:
                                  GeneratedKalkulatorAjaibMatematikaWidget2(),
                            ),
                            Positioned(
                              left: 69.0,
                              top: 21.0,
                              right: null,
                              bottom: null,
                              width: 268.0,
                              height: 35.0,
                              child: GeneratedButtonSearchWidget18(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
