import 'package:flutter/material.dart';
import 'package:flutterapp/atsapp/generatedprofilwidget/generated/GeneratedSukasukasayaWidget.dart';
import 'package:flutterapp/atsapp/generatedprofilwidget/generated/GeneratedLine15Widget.dart';
import 'package:flutterapp/atsapp/generatedprofilwidget/generated/GeneratedNomerTeleponWidget.dart';
import 'package:flutterapp/atsapp/generatedprofilwidget/generated/GeneratedGmailLogoWidget.dart';
import 'package:flutterapp/atsapp/generatedprofilwidget/generated/GeneratedPerempuanWidget.dart';
import 'package:flutterapp/atsapp/generatedprofilwidget/generated/GeneratedAlamatWidget2.dart';
import 'package:flutterapp/atsapp/generatedprofilwidget/generated/GeneratedJlPahlawanNo34Widget1.dart';
import 'package:flutterapp/atsapp/generatedprofilwidget/generated/GeneratedButtonUbahWidget.dart';
import 'package:flutterapp/atsapp/generatedprofilwidget/generated/GeneratedJenisKelaminWidget.dart';
import 'package:flutterapp/atsapp/generatedprofilwidget/generated/GeneratedVectorWidget10.dart';
import 'package:flutterapp/atsapp/generatedprofilwidget/generated/GeneratedProfilWidget1.dart';
import 'package:flutterapp/atsapp/generatedprofilwidget/generated/GeneratedLine17Widget.dart';
import 'package:flutterapp/atsapp/generatedprofilwidget/generated/GeneratedMenuWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/atsapp/generatedprofilwidget/generated/GeneratedSukasukagmailcomWidget.dart';
import 'package:flutterapp/atsapp/generatedprofilwidget/generated/GeneratedButtonLogoutWidget.dart';
import 'package:flutterapp/atsapp/generatedprofilwidget/generated/GeneratedLine12Widget.dart';
import 'package:flutterapp/atsapp/generatedprofilwidget/generated/Generated621Widget.dart';
import 'package:flutterapp/atsapp/generatedprofilwidget/generated/GeneratedIPhone14Widget.dart';
import 'package:flutterapp/atsapp/generatedprofilwidget/generated/GeneratedEmailWidget4.dart';
import 'package:flutterapp/atsapp/generatedprofilwidget/generated/GeneratedLine16Widget.dart';
import 'package:flutterapp/atsapp/generatedprofilwidget/generated/GeneratedLine18Widget.dart';
import 'package:flutterapp/atsapp/generatedprofilwidget/generated/GeneratedFotoprofilWidget.dart';
import 'package:flutterapp/atsapp/generatedprofilwidget/generated/GeneratedEOS_HOME_OUTLINEDWidget.dart';

/* Frame Profil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfilWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(63, 0, 0, 0),
            offset: Offset(0.0, 4.0),
            blurRadius: 4.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 667.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 26.0,
                  top: 61.0,
                  right: null,
                  bottom: null,
                  width: 122.0,
                  height: 35.0,
                  child: GeneratedProfilWidget1(),
                ),
                Positioned(
                  left: 31.987503051757812,
                  top: 284.0252990722656,
                  right: null,
                  bottom: null,
                  width: 312.0256652832031,
                  height: 1.0,
                  child: GeneratedLine12Widget(),
                ),
                Positioned(
                  left: 32.0,
                  top: 356.0,
                  right: null,
                  bottom: null,
                  width: 312.0256652832031,
                  height: 1.0,
                  child: GeneratedLine16Widget(),
                ),
                Positioned(
                  left: 32.0,
                  top: 430.0,
                  right: null,
                  bottom: null,
                  width: 312.0256652832031,
                  height: 1.0,
                  child: GeneratedLine17Widget(),
                ),
                Positioned(
                  left: 32.0,
                  top: 508.0,
                  right: null,
                  bottom: null,
                  width: 312.0256652832031,
                  height: 1.0,
                  child: GeneratedLine18Widget(),
                ),
                Positioned(
                  left: 75.0,
                  top: 210.0,
                  right: null,
                  bottom: null,
                  width: 225.00222778320312,
                  height: 1.0,
                  child: GeneratedLine15Widget(),
                ),
                Positioned(
                  left: 153.0,
                  top: 99.0,
                  right: null,
                  bottom: null,
                  width: 70.0,
                  height: 70.0,
                  child: GeneratedFotoprofilWidget(),
                ),
                Positioned(
                  left: 260.0,
                  top: 588.0,
                  right: null,
                  bottom: null,
                  width: 84.0,
                  height: 30.0,
                  child: GeneratedButtonUbahWidget(),
                ),
                Positioned(
                  left: 153.0,
                  top: 588.0,
                  right: null,
                  bottom: null,
                  width: 84.0,
                  height: 30.0,
                  child: GeneratedButtonLogoutWidget(),
                ),
                Positioned(
                  left: 26.0,
                  top: 24.0,
                  right: null,
                  bottom: null,
                  width: 25.0,
                  height: 25.0,
                  child: GeneratedMenuWidget2(),
                ),
                Positioned(
                  left: 132.0,
                  top: 186.0,
                  right: null,
                  bottom: null,
                  width: 114.0,
                  height: 17.0,
                  child: GeneratedSukasukasayaWidget(),
                ),
                Positioned(
                  left: 31.0,
                  top: 237.0,
                  right: null,
                  bottom: null,
                  width: 20.0,
                  height: 20.0,
                  child: GeneratedGmailLogoWidget(),
                ),
                Positioned(
                  left: 28.0,
                  top: 381.0,
                  right: null,
                  bottom: null,
                  width: 27.0,
                  height: 26.0,
                  child: GeneratedEOS_HOME_OUTLINEDWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.052777781168619795;
                    double scaleX = (constraints.maxWidth * percentWidth) /
                        19.791667938232422;

                    double percentHeight = 0.025768365817091455;
                    double scaleY =
                        (constraints.maxHeight * percentHeight) / 17.1875;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX:
                              constraints.maxWidth * 0.08533333333333333,
                          translateY:
                              constraints.maxHeight * 0.6911544227886057,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedVectorWidget10())
                    ]);
                  }),
                ),
                Positioned(
                  left: 65.0,
                  top: 237.0,
                  right: null,
                  bottom: null,
                  width: 41.0,
                  height: 19.0,
                  child: GeneratedEmailWidget4(),
                ),
                Positioned(
                  left: 65.0,
                  top: 310.0,
                  right: null,
                  bottom: null,
                  width: 100.0,
                  height: 17.0,
                  child: GeneratedNomerTeleponWidget(),
                ),
                Positioned(
                  left: 65.0,
                  top: 334.0,
                  right: null,
                  bottom: null,
                  width: 105.0,
                  height: 21.0,
                  child: Generated621Widget(),
                ),
                Positioned(
                  left: 67.0,
                  top: 384.0,
                  right: null,
                  bottom: null,
                  width: 80.0,
                  height: 21.0,
                  child: GeneratedAlamatWidget2(),
                ),
                Positioned(
                  left: 63.0,
                  top: 459.0,
                  right: null,
                  bottom: null,
                  width: 93.0,
                  height: 18.0,
                  child: GeneratedJenisKelaminWidget(),
                ),
                Positioned(
                  left: 64.0,
                  top: 485.0,
                  right: null,
                  bottom: null,
                  width: 86.0,
                  height: 22.0,
                  child: GeneratedPerempuanWidget(),
                ),
                Positioned(
                  left: 32.0,
                  top: 314.0,
                  right: null,
                  bottom: null,
                  width: 20.0,
                  height: 20.0,
                  child: GeneratedIPhone14Widget(),
                ),
                Positioned(
                  left: 65.0,
                  top: 260.0,
                  right: null,
                  bottom: null,
                  width: 143.0,
                  height: 18.0,
                  child: GeneratedSukasukagmailcomWidget(),
                ),
                Positioned(
                  left: 66.0,
                  top: 410.0,
                  right: null,
                  bottom: null,
                  width: 120.0,
                  height: 17.0,
                  child: GeneratedJlPahlawanNo34Widget1(),
                )
              ]),
        ),
      ),
    ));
  }
}
