import 'package:flutter/material.dart';
import 'package:flutterapp/atsapp/generatededitprodukwidget/generated/GeneratedStokProdukWidget.dart';
import 'package:flutterapp/atsapp/generatededitprodukwidget/generated/GeneratedButtonEditWidget3.dart';
import 'package:flutterapp/atsapp/generatededitprodukwidget/generated/GeneratedRectangle185Widget1.dart';
import 'package:flutterapp/atsapp/generatededitprodukwidget/generated/GeneratedFotoProdukWidget19.dart';
import 'package:flutterapp/atsapp/generatededitprodukwidget/generated/GeneratedRectangle190Widget2.dart';
import 'package:flutterapp/atsapp/generatededitprodukwidget/generated/GeneratedLine213Widget3.dart';
import 'package:flutterapp/atsapp/generatededitprodukwidget/generated/GeneratedLine212Widget3.dart';
import 'package:flutterapp/atsapp/generatededitprodukwidget/generated/GeneratedLine203Widget3.dart';
import 'package:flutterapp/atsapp/generatededitprodukwidget/generated/GeneratedRectangle188Widget1.dart';
import 'package:flutterapp/atsapp/generatededitprodukwidget/generated/GeneratedButtonEditWidget.dart';
import 'package:flutterapp/atsapp/generatededitprodukwidget/generated/GeneratedLine216Widget.dart';
import 'package:flutterapp/atsapp/generatededitprodukwidget/generated/GeneratedNamaProdukWidget1.dart';
import 'package:flutterapp/atsapp/generatededitprodukwidget/generated/GeneratedRectangle187Widget1.dart';
import 'package:flutterapp/atsapp/generatededitprodukwidget/generated/GeneratedRectangle189Widget4.dart';
import 'package:flutterapp/atsapp/generatededitprodukwidget/generated/GeneratedButtonEditWidget2.dart';
import 'package:flutterapp/atsapp/generatededitprodukwidget/generated/GeneratedRincianProdukWidget3.dart';
import 'package:flutterapp/atsapp/generatededitprodukwidget/generated/GeneratedSimpanWidget.dart';
import 'package:flutterapp/atsapp/generatededitprodukwidget/generated/GeneratedButtonEditWidget1.dart';
import 'package:flutterapp/atsapp/generatededitprodukwidget/generated/GeneratedRectangle135Widget10.dart';
import 'package:flutterapp/atsapp/generatededitprodukwidget/generated/GeneratedLine214Widget.dart';
import 'package:flutterapp/atsapp/generatededitprodukwidget/generated/GeneratedRectangle186Widget1.dart';

/* Frame Edit Produk
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEditProdukWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 312.0,
                right: null,
                bottom: null,
                width: 375.0013427734375,
                height: 1.0,
                child: GeneratedLine203Widget3(),
              ),
              Positioned(
                left: 54.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 261.0,
                height: 249.0,
                child: GeneratedFotoProdukWidget19(),
              ),
              Positioned(
                left: 26.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 275.0,
                height: 17.0,
                child: GeneratedNamaProdukWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 356.0458984375,
                right: null,
                bottom: null,
                width: 374.9998779296875,
                height: 1.0,
                child: GeneratedLine214Widget(),
              ),
              Positioned(
                left: -1.0,
                top: 398.0458984375,
                right: null,
                bottom: null,
                width: 374.9998779296875,
                height: 1.0,
                child: GeneratedLine212Widget3(),
              ),
              Positioned(
                left: 1.0,
                top: 523.0458984375,
                right: null,
                bottom: null,
                width: 374.9998779296875,
                height: 1.0,
                child: GeneratedLine216Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 617.0458984375,
                right: null,
                bottom: null,
                width: 374.9998779296875,
                height: 1.0,
                child: GeneratedLine213Widget3(),
              ),
              Positioned(
                left: 27.0,
                top: 366.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 21.0,
                child: GeneratedRincianProdukWidget3(),
              ),
              Positioned(
                left: 26.0,
                top: 531.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 21.0,
                child: GeneratedStokProdukWidget(),
              ),
              Positioned(
                left: 27.0,
                top: 412.0,
                right: null,
                bottom: null,
                width: 247.0,
                height: 17.0,
                child: GeneratedRectangle135Widget10(),
              ),
              Positioned(
                left: 55.0,
                top: 556.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 17.0,
                child: GeneratedRectangle190Widget2(),
              ),
              Positioned(
                left: 27.0,
                top: 434.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 17.0,
                child: GeneratedRectangle185Widget1(),
              ),
              Positioned(
                left: 27.0,
                top: 456.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 17.0,
                child: GeneratedRectangle186Widget1(),
              ),
              Positioned(
                left: 27.0,
                top: 478.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 17.0,
                child: GeneratedRectangle187Widget1(),
              ),
              Positioned(
                left: 27.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 17.0,
                child: GeneratedRectangle188Widget1(),
              ),
              Positioned(
                left: 211.0,
                top: 622.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 36.0,
                child: GeneratedRectangle189Widget4(),
              ),
              Positioned(
                left: 232.0,
                top: 632.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 19.0,
                child: GeneratedSimpanWidget(),
              ),
              Positioned(
                left: 26.0,
                top: 281.0,
                right: null,
                bottom: null,
                width: 16.000001907348633,
                height: 16.0,
                child: GeneratedButtonEditWidget(),
              ),
              Positioned(
                left: 27.0,
                top: 556.0,
                right: null,
                bottom: null,
                width: 16.000001907348633,
                height: 16.0,
                child: GeneratedButtonEditWidget1(),
              ),
              Positioned(
                left: 143.0,
                top: 557.0,
                right: null,
                bottom: null,
                width: 16.000001907348633,
                height: 16.0,
                child: GeneratedButtonEditWidget2(),
              ),
              Positioned(
                left: 50.0,
                top: 281.0,
                right: null,
                bottom: null,
                width: 16.000001907348633,
                height: 16.0,
                child: GeneratedButtonEditWidget3(),
              )
            ]),
      ),
    ));
  }
}
