import 'package:flutter/material.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedButtonBeliWidget5.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedMenuWidget7.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedFotoProdukWidget9.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedRp18000Widget1.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedButtonSearchWidget6.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedButtonBeliWidget6.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedRp22000Widget.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedButtonBeliWidget8.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedNotebookMemakaiBajuBulpenWidget.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedRp12000Widget.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedButtonBeliWidget11.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedRp20000Widget1.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedFotoProdukWidget10.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedAddBasketWidget10.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedNotebookRollerBinderWidget1.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedAddBasketWidget9.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedFotoProdukWidget6.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedAddBasketWidget6.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedNotebookBajuTartanWidget2.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedNotebookRollerPolozWidget.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedNotebookBajuBiruWidget.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedFotoProdukWidget8.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedFotoProdukWidget5.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedNotebookPunyaTaliWidget.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedButtonBeliWidget7.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedNotebookWidget1.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedFotoProdukWidget7.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedButtonBeliWidget10.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedNotebookRollerCanteqWidget1.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedButtonBeliWidget9.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedRp11000Widget.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedRp16000Widget2.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedAddBasketWidget5.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedAddBasketWidget11.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedFotoProdukWidget4.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedAddBasketWidget7.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedAddBasketWidget8.dart';
import 'package:flutterapp/atsapp/generatedlamanhasilpencarianwidget/generated/GeneratedRp19000Widget1.dart';

/* Frame Laman Hasil Pencarian
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLamanHasilPencarianWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1123.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1123.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2853333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0943900267141585;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.07466666666666667,
                                      y: constraints.maxHeight *
                                          0.08281389136242208,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedFotoProdukWidget4(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2853333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0943900267141585;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.07466666666666667,
                                      y: constraints.maxHeight *
                                          0.21104185218165628,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedFotoProdukWidget5(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2853333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0943900267141585;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.07733333333333334,
                                      y: constraints.maxHeight *
                                          0.3428317008014248,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedFotoProdukWidget6(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2853333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0943900267141585;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.07733333333333334,
                                      y: constraints.maxHeight *
                                          0.4764024933214604,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedFotoProdukWidget7(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2853333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0943900267141585;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.07466666666666667,
                                      y: constraints.maxHeight *
                                          0.6090828138913624,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedFotoProdukWidget8(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2853333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0943900267141585;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.08533333333333333,
                                      y: constraints.maxHeight *
                                          0.7417631344612645,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedFotoProdukWidget9(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2853333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0943900267141585;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.096,
                                      y: constraints.maxHeight *
                                          0.8744434550311665,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedFotoProdukWidget10(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 28.0,
                              top: 28.0,
                              right: null,
                              bottom: null,
                              width: 25.0,
                              height: 25.0,
                              child: GeneratedMenuWidget7(),
                            ),
                            Positioned(
                              left: 203.0,
                              top: 173.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 27.0,
                              child: GeneratedButtonBeliWidget5(),
                            ),
                            Positioned(
                              left: 203.0,
                              top: 320.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 27.0,
                              child: GeneratedButtonBeliWidget6(),
                            ),
                            Positioned(
                              left: 203.0,
                              top: 464.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 27.0,
                              child: GeneratedButtonBeliWidget7(),
                            ),
                            Positioned(
                              left: 203.0,
                              top: 614.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 27.0,
                              child: GeneratedButtonBeliWidget8(),
                            ),
                            Positioned(
                              left: 203.0,
                              top: 763.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 27.0,
                              child: GeneratedButtonBeliWidget9(),
                            ),
                            Positioned(
                              left: 203.0,
                              top: 912.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 27.0,
                              child: GeneratedButtonBeliWidget10(),
                            ),
                            Positioned(
                              left: 203.0,
                              top: 1057.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 27.0,
                              child: GeneratedButtonBeliWidget11(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 94.0,
                              right: null,
                              bottom: null,
                              width: 151.0,
                              height: 21.0,
                              child: GeneratedNotebookRollerCanteqWidget1(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 125.0,
                              right: null,
                              bottom: null,
                              width: 75.0,
                              height: 19.0,
                              child: GeneratedRp16000Widget2(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 268.0,
                              right: null,
                              bottom: null,
                              width: 75.0,
                              height: 19.0,
                              child: GeneratedRp18000Widget1(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 416.0,
                              right: null,
                              bottom: null,
                              width: 75.0,
                              height: 19.0,
                              child: GeneratedRp12000Widget(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 566.0,
                              right: null,
                              bottom: null,
                              width: 75.0,
                              height: 19.0,
                              child: GeneratedRp19000Widget1(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 728.0,
                              right: null,
                              bottom: null,
                              width: 75.0,
                              height: 19.0,
                              child: GeneratedRp20000Widget1(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 871.0,
                              right: null,
                              bottom: null,
                              width: 75.0,
                              height: 19.0,
                              child: GeneratedRp22000Widget(),
                            ),
                            Positioned(
                              left: 162.0,
                              top: 1013.0,
                              right: null,
                              bottom: null,
                              width: 75.0,
                              height: 19.0,
                              child: GeneratedRp11000Widget(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 239.0,
                              right: null,
                              bottom: null,
                              width: 128.0,
                              height: 20.0,
                              child: GeneratedNotebookPunyaTaliWidget(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 385.0,
                              right: null,
                              bottom: null,
                              width: 133.0,
                              height: 20.0,
                              child: GeneratedNotebookRollerPolozWidget(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 535.0,
                              right: null,
                              bottom: null,
                              width: 141.0,
                              height: 20.0,
                              child: GeneratedNotebookRollerBinderWidget1(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 684.0,
                              right: null,
                              bottom: null,
                              width: 129.0,
                              height: 38.0,
                              child: GeneratedNotebookMemakaiBajuBulpenWidget(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 833.0,
                              right: null,
                              bottom: null,
                              width: 144.0,
                              height: 20.0,
                              child: GeneratedNotebookBajuTartanWidget2(),
                            ),
                            Positioned(
                              left: 162.0,
                              top: 983.0,
                              right: null,
                              bottom: null,
                              width: 144.0,
                              height: 20.0,
                              child: GeneratedNotebookBajuBiruWidget(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 173.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedAddBasketWidget5(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 320.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedAddBasketWidget6(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 464.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedAddBasketWidget7(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 614.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedAddBasketWidget8(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 763.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedAddBasketWidget9(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 912.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedAddBasketWidget10(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 1057.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedAddBasketWidget11(),
                            ),
                            Positioned(
                              left: 69.0,
                              top: 23.0,
                              right: null,
                              bottom: null,
                              width: 268.0,
                              height: 35.0,
                              child: GeneratedButtonSearchWidget6(),
                            ),
                            Positioned(
                              left: 89.0,
                              top: 31.0,
                              right: null,
                              bottom: null,
                              width: 64.0,
                              height: 23.0,
                              child: GeneratedNotebookWidget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
