import 'package:flutter/material.dart';
import 'package:flutterapp/atsapp/generatedpesananwidget/generated/GeneratedStatusWidget1.dart';
import 'package:flutterapp/atsapp/generatedpesananwidget/generated/GeneratedButtonSudahDiterimaWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/atsapp/generatedpesananwidget/generated/GeneratedStatusWidget.dart';
import 'package:flutterapp/atsapp/generatedpesananwidget/generated/GeneratedRectangle71Widget2.dart';
import 'package:flutterapp/atsapp/generatedpesananwidget/generated/GeneratedMenuWidget8.dart';
import 'package:flutterapp/atsapp/generatedpesananwidget/generated/GeneratedNotebookBajuTartanWidget3.dart';
import 'package:flutterapp/atsapp/generatedpesananwidget/generated/GeneratedDiKirimWidget.dart';
import 'package:flutterapp/atsapp/generatedpesananwidget/generated/GeneratedRectangle203Widget.dart';
import 'package:flutterapp/atsapp/generatedpesananwidget/generated/GeneratedButtonSudahDiterimaWidget.dart';
import 'package:flutterapp/atsapp/generatedpesananwidget/generated/GeneratedSelesaiWidget1.dart';
import 'package:flutterapp/atsapp/generatedpesananwidget/generated/GeneratedPesananWidget1.dart';
import 'package:flutterapp/atsapp/generatedpesananwidget/generated/GeneratedStatusWidget2.dart';
import 'package:flutterapp/atsapp/generatedpesananwidget/generated/GeneratedRectangle204Widget.dart';
import 'package:flutterapp/atsapp/generatedpesananwidget/generated/GeneratedPenghapusHitamManizWidget.dart';

/* Frame Pesanan
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPesananWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2853333333333333;

                  final double height =
                      constraints.maxHeight * 0.15892053973013492;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.064,
                        y: constraints.maxHeight * 0.12593703148425786,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle71Widget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2853333333333333;

                  final double height =
                      constraints.maxHeight * 0.15892053973013492;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.064,
                        y: constraints.maxHeight * 0.34182908545727136,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle204Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.32;

                  final double height =
                      constraints.maxHeight * 0.04047976011994003;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.416,
                        y: constraints.maxHeight * 0.22788605697151423,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedButtonSudahDiterimaWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.32;

                  final double height =
                      constraints.maxHeight * 0.04047976011994003;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.41333333333333333,
                        y: constraints.maxHeight * 0.43778110944527737,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedButtonSudahDiterimaWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.08545727136431784;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle203Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.06666666666666667;

                  final double height =
                      constraints.maxHeight * 0.037481259370314844;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.064,
                        y: constraints.maxHeight * 0.0239880059970015,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedMenuWidget8(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.25333333333333335;

                  final double height =
                      constraints.maxHeight * 0.044977511244377814;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.17333333333333334,
                        y: constraints.maxHeight * 0.0239880059970015,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedPesananWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.5706666666666667;

                  final double height =
                      constraints.maxHeight * 0.037481259370314844;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.416,
                        y: constraints.maxHeight * 0.12593703148425786,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedNotebookBajuTartanWidget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.5226666666666666;

                  final double height =
                      constraints.maxHeight * 0.037481259370314844;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.41333333333333333,
                        y: constraints.maxHeight * 0.34182908545727136,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedPenghapusHitamManizWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.16533333333333333;

                  final double height =
                      constraints.maxHeight * 0.037481259370314844;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.416,
                        y: constraints.maxHeight * 0.17691154422788605,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedStatusWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.16533333333333333;

                  final double height =
                      constraints.maxHeight * 0.037481259370314844;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.416,
                        y: constraints.maxHeight * 0.17691154422788605,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedStatusWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.16533333333333333;

                  final double height =
                      constraints.maxHeight * 0.037481259370314844;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.416,
                        y: constraints.maxHeight * 0.3823088455772114,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedStatusWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.168;

                  final double height =
                      constraints.maxHeight * 0.037481259370314844;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5946666666666667,
                        y: constraints.maxHeight * 0.17691154422788605,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedDiKirimWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.16266666666666665;

                  final double height =
                      constraints.maxHeight * 0.041979010494752625;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5946666666666667,
                        y: constraints.maxHeight * 0.3823088455772114,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedSelesaiWidget1(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
