import 'package:flutter/material.dart';

/* UndefinedNode No Telepon
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNoTeleponWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
