import 'package:flutter/material.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget/generated/GeneratedShoppingBagWidget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget/generated/GeneratedLine213Widget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget/generated/GeneratedSpesifikasiWidget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget/generated/GeneratedDetailProdukWidget1.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget/generated/GeneratedRectangle135Widget1.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget/generated/GeneratedKertasHVSPutih80GsmWidget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget/generated/GeneratedLine206Widget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget/generated/Generated47Widget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget/generated/GeneratedVectorWidget25.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget/generated/GeneratedNotebookBajuTartanukuranA5Widget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget/generated/GeneratedRectangle178Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget/generated/GeneratedRp22000Widget1.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget/generated/GeneratedMenuWidget10.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget/generated/GeneratedRincianProdukWidget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget/generated/GeneratedLine203Widget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget/generated/Generated2356terjualWidget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget/generated/GeneratedLine207Widget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget/generated/GeneratedLine91Widget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget/generated/GeneratedButtonPesanWidget2.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget/generated/GeneratedUkuran148cmx21cmWidget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget/generated/GeneratedMasukkankekeranjangWidget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget/generated/GeneratedNotebookBajuTartanWidget4.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget/generated/GeneratedIsi50lembar100halamanWidget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget/generated/GeneratedRectangle135Widget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget/generated/GeneratedLine212Widget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget/generated/GeneratedCovertransparant300gsmWidget.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget/generated/GeneratedSpiralputihhitamsampingWidget.dart';

/* Frame Detail Produk
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDetailProdukWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 57.0,
                child: GeneratedRectangle178Widget(),
              ),
              Positioned(
                left: 66.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 169.0,
                height: 28.0,
                child: GeneratedDetailProdukWidget1(),
              ),
              Positioned(
                left: 57.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 261.0,
                height: 249.0,
                child: GeneratedRectangle135Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 312.0,
                right: null,
                bottom: null,
                width: 375.0013427734375,
                height: 1.0,
                child: GeneratedLine203Widget(),
              ),
              Positioned(
                left: 175.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 1.0,
                child: GeneratedLine206Widget(),
              ),
              Positioned(
                left: 277.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 1.0,
                child: GeneratedLine207Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 409.0458984375,
                right: null,
                bottom: null,
                width: 374.9998779296875,
                height: 1.0,
                child: GeneratedLine91Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 454.0458984375,
                right: null,
                bottom: null,
                width: 374.9998779296875,
                height: 1.0,
                child: GeneratedLine212Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 617.0458984375,
                right: null,
                bottom: null,
                width: 374.9998779296875,
                height: 1.0,
                child: GeneratedLine213Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 422.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 21.0,
                child: GeneratedRincianProdukWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 622.0,
                right: null,
                bottom: null,
                width: 168.0,
                height: 36.0,
                child: GeneratedRectangle135Widget1(),
              ),
              Positioned(
                left: 241.0,
                top: 622.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 36.0,
                child: GeneratedButtonPesanWidget2(),
              ),
              Positioned(
                left: 31.0,
                top: 632.0,
                right: null,
                bottom: null,
                width: 159.0,
                height: 20.0,
                child: GeneratedMasukkankekeranjangWidget(),
              ),
              Positioned(
                left: 26.0,
                top: 322.0,
                right: null,
                bottom: null,
                width: 214.0,
                height: 25.0,
                child: GeneratedNotebookBajuTartanWidget4(),
              ),
              Positioned(
                left: 26.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 26.0,
                child: GeneratedRp22000Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.25822222900390623;

                  final double height =
                      constraints.maxHeight * 0.023738130457933874;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06933333333333333,
                        y: constraints.maxHeight * 0.5742128935532234,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup1Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 139.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 21.0,
                child: Generated47Widget(),
              ),
              Positioned(
                left: 184.0,
                top: 384.0,
                right: null,
                bottom: null,
                width: 84.0,
                height: 19.0,
                child: Generated2356terjualWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.048;
                  double scaleX = (constraints.maxWidth * percentWidth) / 18.0;

                  double percentHeight = 0.026986506746626688;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 18.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.824,
                        translateY: constraints.maxHeight * 0.5712143928035982,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget25())
                  ]);
                }),
              ),
              Positioned(
                left: 324.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedShoppingBagWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 467.0,
                right: null,
                bottom: null,
                width: 192.0,
                height: 19.0,
                child: GeneratedNotebookBajuTartanukuranA5Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 488.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 16.0,
                child: GeneratedUkuran148cmx21cmWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 510.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 14.0,
                child: GeneratedSpesifikasiWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 571.0,
                right: null,
                bottom: null,
                width: 192.0,
                height: 19.0,
                child: GeneratedCovertransparant300gsmWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.06666666666666667;

                  final double height =
                      constraints.maxHeight * 0.037481259370314844;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06933333333333333,
                        y: constraints.maxHeight * 0.0239880059970015,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedMenuWidget10(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 21.0,
                top: 531.0,
                right: null,
                bottom: null,
                width: 174.0,
                height: 14.0,
                child: GeneratedKertasHVSPutih80GsmWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 551.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 16.0,
                child: GeneratedIsi50lembar100halamanWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 591.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 19.0,
                child: GeneratedSpiralputihhitamsampingWidget(),
              )
            ]),
      ),
    ));
  }
}
