import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/helpers/svg/svg.dart';

/* Line Line 139
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLine139Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: TransformHelper.rotate(
            a: 0.83,
            b: -0.55,
            c: 0.55,
            d: 0.83,
            child: Container(
              width: 25.238859176635742,
              height: 1.0,
              child: SvgWidget(painters: [
                SvgPathPainter.stroke(
                  1.0,
                  strokeJoin: StrokeJoin.miter,
                )
                  ..addPath('M0 0L25.2389 0L25.2389 -1L0 -1L0 0Z')
                  ..color = Color.fromARGB(255, 0, 0, 0),
              ]),
            )));
  }
}
