import 'package:flutter/material.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget6/generated/GeneratedButtonSearchWidget15.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget6/generated/GeneratedButtonOrigamiWidget2.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget6/generated/GeneratedButtonKategoriBusurJangkaWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget6/generated/GeneratedButtonKategoriPenggarisWidget2.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget6/generated/GeneratedMenuWidget19.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget6/generated/GeneratedButtonKategoriPensilWidget2.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget6/generated/GeneratedButtonKategoriBukuWidget2.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget6/generated/GeneratedButtonKategoriNotebookWidget2.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget6/generated/GeneratedButtonKategoriBulpenWidget2.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget6/generated/GeneratedButtonKategoriPenghapusWidget2.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget6/generated/GeneratedButtonKategoriMapBerkasWidget2.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget6/generated/GeneratedJelajahWidget7.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget6/generated/GeneratedButtonKategoriAlatLukisWidget2.dart';

/* Frame Jelajah
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedJelajahWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(63, 0, 0, 0),
            offset: Offset(0.0, 4.0),
            blurRadius: 4.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 667.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 26.0,
                  top: 66.0,
                  right: null,
                  bottom: null,
                  width: 152.0,
                  height: 49.0,
                  child: GeneratedJelajahWidget7(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.06666666666666667;

                    final double height =
                        constraints.maxHeight * 0.037481259370314844;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.06933333333333333,
                          y: constraints.maxHeight * 0.041979010494752625,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedMenuWidget19(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 26.0,
                  top: 204.0,
                  right: null,
                  bottom: null,
                  width: 80.0,
                  height: 80.0,
                  child: GeneratedButtonKategoriBukuWidget2(),
                ),
                Positioned(
                  left: 143.0,
                  top: 204.0,
                  right: null,
                  bottom: null,
                  width: 80.0,
                  height: 80.0,
                  child: GeneratedButtonKategoriPensilWidget2(),
                ),
                Positioned(
                  left: 264.0,
                  top: 204.0,
                  right: null,
                  bottom: null,
                  width: 80.0,
                  height: 80.0,
                  child: GeneratedButtonKategoriPenghapusWidget2(),
                ),
                Positioned(
                  left: 26.0,
                  top: 320.0,
                  right: null,
                  bottom: null,
                  width: 80.0,
                  height: 80.0,
                  child: GeneratedButtonKategoriBulpenWidget2(),
                ),
                Positioned(
                  left: 26.0,
                  top: 436.0,
                  right: null,
                  bottom: null,
                  width: 80.0,
                  height: 80.0,
                  child: GeneratedButtonKategoriNotebookWidget2(),
                ),
                Positioned(
                  left: 143.0,
                  top: 552.0,
                  right: null,
                  bottom: null,
                  width: 80.0,
                  height: 80.0,
                  child: GeneratedButtonOrigamiWidget2(),
                ),
                Positioned(
                  left: 264.0,
                  top: 436.0,
                  right: null,
                  bottom: null,
                  width: 80.0,
                  height: 80.0,
                  child: GeneratedButtonKategoriMapBerkasWidget2(),
                ),
                Positioned(
                  left: 143.0,
                  top: 436.0,
                  right: null,
                  bottom: null,
                  width: 80.0,
                  height: 80.0,
                  child: GeneratedButtonKategoriBusurJangkaWidget2(),
                ),
                Positioned(
                  left: 143.0,
                  top: 320.0,
                  right: null,
                  bottom: null,
                  width: 80.0,
                  height: 80.0,
                  child: GeneratedButtonKategoriPenggarisWidget2(),
                ),
                Positioned(
                  left: 264.0,
                  top: 320.0,
                  right: null,
                  bottom: null,
                  width: 80.0,
                  height: 80.0,
                  child: GeneratedButtonKategoriAlatLukisWidget2(),
                ),
                Positioned(
                  left: 53.0,
                  top: 123.0,
                  right: null,
                  bottom: null,
                  width: 268.0,
                  height: 35.0,
                  child: GeneratedButtonSearchWidget15(),
                )
              ]),
        ),
      ),
    ));
  }
}
