import 'package:flutter/material.dart';

/* Text Text
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTextWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.2102272510528564,
        fontSize: 12.0,
        fontFamily: 'Inter',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
