import 'package:flutter/material.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget6/generated/GeneratedCovertransparant300gsmWidget2.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget6/generated/GeneratedRp22000Widget4.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget6/generated/GeneratedSpesifikasiWidget2.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget6/generated/GeneratedUkuran148cmx21cmWidget2.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget6/generated/GeneratedMenuWidget20.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget6/generated/GeneratedRincianProdukWidget4.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget6/generated/GeneratedLine207Widget2.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget6/generated/GeneratedButtonPesanWidget4.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget6/generated/GeneratedRectangle135Widget12.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget6/generated/GeneratedLine203Widget4.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget6/generated/Generated47Widget2.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget6/generated/GeneratedNotebookBajuTartanWidget7.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget6/generated/GeneratedRectangle135Widget11.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget6/generated/GeneratedVectorWidget47.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget6/generated/GeneratedDetailProdukWidget7.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget6/generated/GeneratedMasukkankekeranjangWidget2.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget6/generated/GeneratedRectangle178Widget3.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget6/generated/GeneratedNotebookBajuTartanukuranA5Widget2.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget6/generated/GeneratedShoppingBagWidget3.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget6/generated/GeneratedLine206Widget3.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget6/generated/GeneratedLine212Widget4.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget6/generated/Generated2356terjualWidget1.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget6/generated/GeneratedLine91Widget4.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget6/generated/GeneratedGroup1Widget6.dart';
import 'package:flutterapp/atsapp/generateddetailprodukwidget6/generated/GeneratedLine213Widget4.dart';

/* Frame Detail Produk
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDetailProdukWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 57.0,
                child: GeneratedRectangle178Widget3(),
              ),
              Positioned(
                left: 66.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 169.0,
                height: 28.0,
                child: GeneratedDetailProdukWidget7(),
              ),
              Positioned(
                left: 57.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 261.0,
                height: 249.0,
                child: GeneratedRectangle135Widget11(),
              ),
              Positioned(
                left: 0.0,
                top: 312.0,
                right: null,
                bottom: null,
                width: 375.0013427734375,
                height: 1.0,
                child: GeneratedLine203Widget4(),
              ),
              Positioned(
                left: 175.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 1.0,
                child: GeneratedLine206Widget3(),
              ),
              Positioned(
                left: 277.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 1.0,
                child: GeneratedLine207Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 409.0458984375,
                right: null,
                bottom: null,
                width: 374.9998779296875,
                height: 1.0,
                child: GeneratedLine91Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 454.0458984375,
                right: null,
                bottom: null,
                width: 374.9998779296875,
                height: 1.0,
                child: GeneratedLine212Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 617.0458984375,
                right: null,
                bottom: null,
                width: 374.9998779296875,
                height: 1.0,
                child: GeneratedLine213Widget4(),
              ),
              Positioned(
                left: 25.0,
                top: 422.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 21.0,
                child: GeneratedRincianProdukWidget4(),
              ),
              Positioned(
                left: 25.0,
                top: 622.0,
                right: null,
                bottom: null,
                width: 168.0,
                height: 36.0,
                child: GeneratedRectangle135Widget12(),
              ),
              Positioned(
                left: 241.0,
                top: 622.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 36.0,
                child: GeneratedButtonPesanWidget4(),
              ),
              Positioned(
                left: 31.0,
                top: 632.0,
                right: null,
                bottom: null,
                width: 159.0,
                height: 20.0,
                child: GeneratedMasukkankekeranjangWidget2(),
              ),
              Positioned(
                left: 26.0,
                top: 322.0,
                right: null,
                bottom: null,
                width: 214.0,
                height: 25.0,
                child: GeneratedNotebookBajuTartanWidget7(),
              ),
              Positioned(
                left: 26.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 26.0,
                child: GeneratedRp22000Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.25822222900390623;

                  final double height =
                      constraints.maxHeight * 0.023738130457933874;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06933333333333333,
                        y: constraints.maxHeight * 0.5742128935532234,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup1Widget6(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 139.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 21.0,
                child: Generated47Widget2(),
              ),
              Positioned(
                left: 184.0,
                top: 384.0,
                right: null,
                bottom: null,
                width: 84.0,
                height: 19.0,
                child: Generated2356terjualWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.048;
                  double scaleX = (constraints.maxWidth * percentWidth) / 18.0;

                  double percentHeight = 0.026986506746626688;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 18.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.824,
                        translateY: constraints.maxHeight * 0.5712143928035982,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget47())
                  ]);
                }),
              ),
              Positioned(
                left: 324.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedShoppingBagWidget3(),
              ),
              Positioned(
                left: 25.0,
                top: 467.0,
                right: null,
                bottom: null,
                width: 192.0,
                height: 19.0,
                child: GeneratedNotebookBajuTartanukuranA5Widget2(),
              ),
              Positioned(
                left: 25.0,
                top: 488.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 16.0,
                child: GeneratedUkuran148cmx21cmWidget2(),
              ),
              Positioned(
                left: 25.0,
                top: 510.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 14.0,
                child: GeneratedSpesifikasiWidget2(),
              ),
              Positioned(
                left: 21.0,
                top: 571.0,
                right: null,
                bottom: null,
                width: 192.0,
                height: 19.0,
                child: GeneratedCovertransparant300gsmWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.06666666666666667;

                  final double height =
                      constraints.maxHeight * 0.037481259370314844;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06933333333333333,
                        y: constraints.maxHeight * 0.0239880059970015,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedMenuWidget20(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
