import 'package:flutter/material.dart';

/* UndefinedNode password
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPasswordWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
