import 'package:flutter/material.dart';
import 'package:flutterapp/atsapp/generatedmenuwidget11/generated/GeneratedEOS_HOME_OUTLINEDWidget1.dart';
import 'package:flutterapp/atsapp/generatedmenuwidget11/generated/GeneratedLine18Widget1.dart';
import 'package:flutterapp/atsapp/generatedmenuwidget11/generated/GeneratedBerandaWidget2.dart';
import 'package:flutterapp/atsapp/generatedmenuwidget11/generated/GeneratedLine21Widget.dart';
import 'package:flutterapp/atsapp/generatedmenuwidget11/generated/GeneratedButtonKeranjangWidget.dart';
import 'package:flutterapp/atsapp/generatedmenuwidget11/generated/GeneratedLine20Widget.dart';
import 'package:flutterapp/atsapp/generatedmenuwidget11/generated/GeneratedLine19Widget.dart';
import 'package:flutterapp/atsapp/generatedmenuwidget11/generated/GeneratedVectorWidget27.dart';
import 'package:flutterapp/atsapp/generatedmenuwidget11/generated/GeneratedStationaryBookWidget.dart';
import 'package:flutterapp/atsapp/generatedmenuwidget11/generated/GeneratedButtonPesananWidget.dart';
import 'package:flutterapp/atsapp/generatedmenuwidget11/generated/GeneratedLine17Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/atsapp/generatedmenuwidget11/generated/GeneratedJelajahWidget2.dart';
import 'package:flutterapp/atsapp/generatedmenuwidget11/generated/GeneratedVectorWidget28.dart';
import 'package:flutterapp/atsapp/generatedmenuwidget11/generated/GeneratedProfilWidget2.dart';
import 'package:flutterapp/atsapp/generatedmenuwidget11/generated/GeneratedMenuWidget12.dart';

/* Frame Menu
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMenuWidget11 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.only(
        topLeft: Radius.circular(0.0),
        topRight: Radius.circular(11.0),
        bottomRight: Radius.circular(11.0),
        bottomLeft: Radius.circular(0.0),
      ),
      child: Container(
        width: 309.0,
        height: 667.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.only(
            topLeft: Radius.circular(0.0),
            topRight: Radius.circular(11.0),
            bottomRight: Radius.circular(11.0),
            bottomLeft: Radius.circular(0.0),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(0.0),
                  topRight: Radius.circular(11.0),
                  bottomRight: Radius.circular(11.0),
                  bottomLeft: Radius.circular(0.0),
                ),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.08090614886731391;

                  final double height =
                      constraints.maxHeight * 0.037481259370314844;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.08090614886731391,
                        y: constraints.maxHeight * 0.034482758620689655,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedMenuWidget12(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.48220064724919093;

                  final double height =
                      constraints.maxHeight * 0.04047976011994003;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.45307443365695793,
                        y: constraints.maxHeight * 0.034482758620689655,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedStationaryBookWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.08737864077669903;

                  final double height =
                      constraints.maxHeight * 0.038980509745127435;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.08090614886731391,
                        y: constraints.maxHeight * 0.12443778110944528,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedEOS_HOME_OUTLINEDWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.8349765419574231;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      258.00775146484375;

                  double percentHeight = 0.0014992503748125937;
                  double scaleY = (constraints.maxHeight * percentHeight) / 1.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.08090614886731391,
                        translateY: constraints.maxHeight * 0.1679160419790105,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedLine17Widget1())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.8349765419574231;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      258.00775146484375;

                  double percentHeight = 0.0014992503748125937;
                  double scaleY = (constraints.maxHeight * percentHeight) / 1.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.08090614886731391,
                        translateY: constraints.maxHeight * 0.24887556221889057,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedLine18Widget1())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.8349765419574231;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      258.00775146484375;

                  double percentHeight = 0.0014992503748125937;
                  double scaleY = (constraints.maxHeight * percentHeight) / 1.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.08090614886731391,
                        translateY: constraints.maxHeight * 0.328335832083958,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedLine19Widget())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.8349765419574231;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      258.00775146484375;

                  double percentHeight = 0.0014992503748125937;
                  double scaleY = (constraints.maxHeight * percentHeight) / 1.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.08090614886731391,
                        translateY: constraints.maxHeight * 0.4017991004497751,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedLine20Widget())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.8349765419574231;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      258.00775146484375;

                  double percentHeight = 0.0014992503748125937;
                  double scaleY = (constraints.maxHeight * percentHeight) / 1.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.08090614886731391,
                        translateY: constraints.maxHeight * 0.4767616191904048,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedLine21Widget())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.22006472491909385;

                  final double height =
                      constraints.maxHeight * 0.0239880059970015;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.20711974110032363,
                        y: constraints.maxHeight * 0.13493253373313344,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedBerandaWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.0566019410068549;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      17.489999771118164;

                  double percentHeight = 0.026221888712321086;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      17.489999771118164;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.08737864077669903,
                        translateY: constraints.maxHeight * 0.21139430284857572,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget27())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.23948220064724918;

                  final double height =
                      constraints.maxHeight * 0.025487256371814093;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.18770226537216828,
                        y: constraints.maxHeight * 0.21739130434782608,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedJelajahWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.3592233009708738;

                  final double height =
                      constraints.maxHeight * 0.035982008995502246;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.08090614886731391,
                        y: constraints.maxHeight * 0.28785607196401797,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedButtonKeranjangWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.32362459546925565;

                  final double height =
                      constraints.maxHeight * 0.035982008995502246;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.08090614886731391,
                        y: constraints.maxHeight * 0.3613193403298351,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedButtonPesananWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06405070530172305;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      19.791667938232422;

                  double percentHeight = 0.025768365817091455;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 17.1875;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.0970873786407767,
                        translateY: constraints.maxHeight * 0.44227886056971516,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget28())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.11974110032362459;

                  final double height =
                      constraints.maxHeight * 0.0239880059970015;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.22653721682847897,
                        y: constraints.maxHeight * 0.44677661169415295,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedProfilWidget2(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
