import 'package:flutter/material.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/GeneratedDiskon30untuksemuaproduklohWidget1.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/GeneratedAddBasketWidget13.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/GeneratedAddBasketWidget15.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/GeneratedAddBasketWidget14.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/GeneratedRp14000Widget1.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/GeneratedFotoProdukWidget11.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/GeneratedFotoProduk3Widget1.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/GeneratedRp18000Widget2.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/GeneratedFotoProduk2Widget1.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/GeneratedBerandaWidget5.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/GeneratedButtonBeliWidget12.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/GeneratedRp16000Widget3.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/GeneratedBannerWidget3.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/GeneratedAddBasketWidget16.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/GeneratedPensilset7pcsWidget1.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/GeneratedNotebookSummerBreezeWidget1.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/GeneratedButtonSearchWidget9.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/GeneratedFotoProduk4Widget1.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/Generated1SetALatLukisLengkapWidget1.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/GeneratedRp13000Widget2.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/GeneratedKalkulatorAjaibMatematikaWidget1.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/GeneratedFotoProduk5Widget1.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/GeneratedButtonBeliWidget16.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/GeneratedBrushpen1Set10pcsWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/GeneratedDiskon50BacktoSchoolWidget1.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/GeneratedBannerWidget2.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/GeneratedButtonBeliWidget13.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/GeneratedButtonBeliWidget14.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/GeneratedAddBasketWidget12.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/GeneratedButtonBeliWidget15.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/GeneratedTrendingWidget1.dart';
import 'package:flutterapp/atsapp/generatedberandawidget4/generated/GeneratedRp45000Widget1.dart';

/* Frame Beranda
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBerandaWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1123.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1123.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 26.0,
                              top: 56.0,
                              right: null,
                              bottom: null,
                              width: 148.0,
                              height: 36.0,
                              child: GeneratedBerandaWidget5(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 97.0,
                              right: null,
                              bottom: null,
                              width: 135.0,
                              height: 190.00001525878906,
                              child: GeneratedBannerWidget2(),
                            ),
                            Positioned(
                              left: 203.0,
                              top: 97.0,
                              right: null,
                              bottom: null,
                              width: 135.0,
                              height: 190.0,
                              child: GeneratedBannerWidget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2853333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0943900267141585;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.377560106856634,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedFotoProdukWidget11(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2853333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0943900267141585;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.5004452359750667,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedFotoProduk2Widget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2853333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0943900267141585;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.6233303650934996,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedFotoProduk3Widget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2853333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0943900267141585;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.7462154942119323,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedFotoProduk4Widget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.2853333333333333;

                                final double height =
                                    constraints.maxHeight * 0.0943900267141585;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.06666666666666667,
                                      y: constraints.maxHeight *
                                          0.8691006233303651,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedFotoProduk5Widget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 26.0,
                              top: 382.0,
                              right: null,
                              bottom: null,
                              width: 128.0,
                              height: 30.0,
                              child: GeneratedTrendingWidget1(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 305.0,
                              right: null,
                              bottom: null,
                              width: 142.0,
                              height: 46.0,
                              child:
                                  GeneratedDiskon30untuksemuaproduklohWidget1(),
                            ),
                            Positioned(
                              left: 203.0,
                              top: 305.0,
                              right: null,
                              bottom: null,
                              width: 101.0,
                              height: 42.0,
                              child: GeneratedDiskon50BacktoSchoolWidget1(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 426.0,
                              right: null,
                              bottom: null,
                              width: 191.0,
                              height: 14.0,
                              child: GeneratedNotebookSummerBreezeWidget1(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 458.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 21.0,
                              child: GeneratedRp16000Widget3(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 593.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 21.0,
                              child: GeneratedRp45000Widget1(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 727.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 21.0,
                              child: GeneratedRp13000Widget2(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 870.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 21.0,
                              child: GeneratedRp14000Widget1(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 1008.0,
                              right: null,
                              bottom: null,
                              width: 93.0,
                              height: 21.0,
                              child: GeneratedRp18000Widget2(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 562.0,
                              right: null,
                              bottom: null,
                              width: 162.0,
                              height: 22.0,
                              child: Generated1SetALatLukisLengkapWidget1(),
                            ),
                            Positioned(
                              left: 200.0,
                              top: 503.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 27.0,
                              child: GeneratedButtonBeliWidget12(),
                            ),
                            Positioned(
                              left: 200.0,
                              top: 645.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 27.0,
                              child: GeneratedButtonBeliWidget13(),
                            ),
                            Positioned(
                              left: 200.0,
                              top: 779.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 27.0,
                              child: GeneratedButtonBeliWidget14(),
                            ),
                            Positioned(
                              left: 200.0,
                              top: 915.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 27.0,
                              child: GeneratedButtonBeliWidget15(),
                            ),
                            Positioned(
                              left: 200.0,
                              top: 1055.0,
                              right: null,
                              bottom: null,
                              width: 78.0,
                              height: 27.0,
                              child: GeneratedButtonBeliWidget16(),
                            ),
                            Positioned(
                              left: 154.0,
                              top: 699.0,
                              right: null,
                              bottom: null,
                              width: 145.0,
                              height: 23.0,
                              child: GeneratedBrushpen1Set10pcsWidget1(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 840.0,
                              right: null,
                              bottom: null,
                              width: 109.0,
                              height: 20.0,
                              child: GeneratedPensilset7pcsWidget1(),
                            ),
                            Positioned(
                              left: 156.0,
                              top: 978.0,
                              right: null,
                              bottom: null,
                              width: 178.0,
                              height: 20.0,
                              child:
                                  GeneratedKalkulatorAjaibMatematikaWidget1(),
                            ),
                            Positioned(
                              left: 69.0,
                              top: 21.0,
                              right: null,
                              bottom: null,
                              width: 268.0,
                              height: 35.0,
                              child: GeneratedButtonSearchWidget9(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 503.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedAddBasketWidget12(),
                            ),
                            Positioned(
                              left: 155.0,
                              top: 645.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedAddBasketWidget13(),
                            ),
                            Positioned(
                              left: 154.0,
                              top: 782.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedAddBasketWidget14(),
                            ),
                            Positioned(
                              left: 156.0,
                              top: 918.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedAddBasketWidget15(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 1055.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedAddBasketWidget16(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
