import 'package:flutter/material.dart';

/* UndefinedNode email
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEmailWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
