import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget/generated/GeneratedButtonKategoriMapBerkasWidget.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget/generated/GeneratedButtonKategoriPenggarisWidget.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget/generated/GeneratedButtonKategoriBusurJangkaWidget.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget/generated/GeneratedButtonKategoriNotebookWidget.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget/generated/GeneratedButtonKategoriBukuWidget.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget/generated/GeneratedJelajahWidget1.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget/generated/GeneratedButtonKategoriPensilWidget.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget/generated/GeneratedMenuWidget.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget/generated/GeneratedButtonKategoriAlatLukisWidget.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget/generated/GeneratedButtonKategoriBulpenWidget.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget/generated/GeneratedButtonKategoriPenghapusWidget.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget/generated/GeneratedButtonOrigamiWidget.dart';
import 'package:flutterapp/atsapp/generatedjelajahwidget/generated/GeneratedButtonSearchWidget.dart';

/* Frame Jelajah
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedJelajahWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(63, 0, 0, 0),
            offset: Offset(0.0, 4.0),
            blurRadius: 4.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 667.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 26.0,
                  top: 66.0,
                  right: null,
                  bottom: null,
                  width: 152.0,
                  height: 49.0,
                  child: GeneratedJelajahWidget1(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.06666666666666667;

                    final double height =
                        constraints.maxHeight * 0.037481259370314844;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.06933333333333333,
                          y: constraints.maxHeight * 0.041979010494752625,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedMenuWidget(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 26.0,
                  top: 204.0,
                  right: null,
                  bottom: null,
                  width: 80.0,
                  height: 80.0,
                  child: GeneratedButtonKategoriBukuWidget(),
                ),
                Positioned(
                  left: 143.0,
                  top: 204.0,
                  right: null,
                  bottom: null,
                  width: 80.0,
                  height: 80.0,
                  child: GeneratedButtonKategoriPensilWidget(),
                ),
                Positioned(
                  left: 264.0,
                  top: 204.0,
                  right: null,
                  bottom: null,
                  width: 80.0,
                  height: 80.0,
                  child: GeneratedButtonKategoriPenghapusWidget(),
                ),
                Positioned(
                  left: 26.0,
                  top: 320.0,
                  right: null,
                  bottom: null,
                  width: 80.0,
                  height: 80.0,
                  child: GeneratedButtonKategoriBulpenWidget(),
                ),
                Positioned(
                  left: 26.0,
                  top: 436.0,
                  right: null,
                  bottom: null,
                  width: 80.0,
                  height: 80.0,
                  child: GeneratedButtonKategoriNotebookWidget(),
                ),
                Positioned(
                  left: 143.0,
                  top: 552.0,
                  right: null,
                  bottom: null,
                  width: 80.0,
                  height: 80.0,
                  child: GeneratedButtonOrigamiWidget(),
                ),
                Positioned(
                  left: 264.0,
                  top: 436.0,
                  right: null,
                  bottom: null,
                  width: 80.0,
                  height: 80.0,
                  child: GeneratedButtonKategoriMapBerkasWidget(),
                ),
                Positioned(
                  left: 143.0,
                  top: 436.0,
                  right: null,
                  bottom: null,
                  width: 80.0,
                  height: 80.0,
                  child: GeneratedButtonKategoriBusurJangkaWidget(),
                ),
                Positioned(
                  left: 143.0,
                  top: 320.0,
                  right: null,
                  bottom: null,
                  width: 80.0,
                  height: 80.0,
                  child: GeneratedButtonKategoriPenggarisWidget(),
                ),
                Positioned(
                  left: 264.0,
                  top: 320.0,
                  right: null,
                  bottom: null,
                  width: 80.0,
                  height: 80.0,
                  child: GeneratedButtonKategoriAlatLukisWidget(),
                ),
                Positioned(
                  left: 53.0,
                  top: 123.0,
                  right: null,
                  bottom: null,
                  width: 268.0,
                  height: 35.0,
                  child: GeneratedButtonSearchWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
