import 'package:flutter/material.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/Generated0Widget1.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/GeneratedMinuslogoWidget2.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/Generated16000Widget.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/GeneratedDeleteWidget.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/GeneratedDikirimkerumahWidget.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/GeneratedDeleteWidget2.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/GeneratedRp13000Widget.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/GeneratedFotoProdukWidget.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/Generated0Widget.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/GeneratedMinuslogoWidget.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/GeneratedButtonCheckoutWidget.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/GeneratedEOS_ADD_CIRCLE_OUTLINEDWidget.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/GeneratedDeleteWidget1.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/GeneratedEllipse5Widget.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/GeneratedFotoProdukWidget2.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/GeneratedMinuslogoWidget1.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/GeneratedNotebookRollerCanteqWidget.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/GeneratedRectangle201Widget.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/GeneratedKeranjangWidget1.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/GeneratedTotalWidget.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/GeneratedRp19000Widget.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/GeneratedEOS_ADD_CIRCLE_OUTLINEDWidget1.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/GeneratedNotebookRollerBinderWidget.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/GeneratedJlPahlawanNo34Widget.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/GeneratedKeranjangmuWidget.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/GeneratedMenuWidget1.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/GeneratedFotoProdukWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/GeneratedGroupWidget.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/GeneratedRp16000Widget.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/GeneratedPensil1set7pcsWidget.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/GeneratedEOS_ADD_CIRCLE_OUTLINEDWidget2.dart';
import 'package:flutterapp/atsapp/generatedkeranjangwidget/generated/Generated1Widget.dart';

/* Frame Keranjang
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKeranjangWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(63, 0, 0, 0),
            offset: Offset(0.0, 4.0),
            blurRadius: 4.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 667.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 26.0,
                  top: 59.0,
                  right: null,
                  bottom: null,
                  width: 172.0,
                  height: 47.0,
                  child: GeneratedKeranjangWidget1(),
                ),
                Positioned(
                  left: 44.0,
                  top: 106.0,
                  right: null,
                  bottom: null,
                  width: 268.0,
                  height: 88.0,
                  child: GeneratedRectangle11Widget(),
                ),
                Positioned(
                  left: 31.0,
                  top: 214.0,
                  right: null,
                  bottom: null,
                  width: 125.0,
                  height: 33.0,
                  child: GeneratedKeranjangmuWidget(),
                ),
                Positioned(
                  left: 70.0,
                  top: 149.0,
                  right: null,
                  bottom: null,
                  width: 135.0,
                  height: 25.0,
                  child: GeneratedJlPahlawanNo34Widget(),
                ),
                Positioned(
                  left: 70.0,
                  top: 121.0,
                  right: null,
                  bottom: null,
                  width: 154.0,
                  height: 21.0,
                  child: GeneratedDikirimkerumahWidget(),
                ),
                Positioned(
                  left: 64.0,
                  top: 247.0,
                  right: null,
                  bottom: null,
                  width: 100.0,
                  height: 100.0,
                  child: GeneratedFotoProdukWidget(),
                ),
                Positioned(
                  left: 64.0,
                  top: 372.0,
                  right: null,
                  bottom: null,
                  width: 100.0,
                  height: 100.0,
                  child: GeneratedFotoProdukWidget1(),
                ),
                Positioned(
                  left: 64.0,
                  top: 497.0,
                  right: null,
                  bottom: null,
                  width: 100.0,
                  height: 100.0,
                  child: GeneratedFotoProdukWidget2(),
                ),
                Positioned(
                  left: 26.0,
                  top: 25.0,
                  right: null,
                  bottom: null,
                  width: 25.0,
                  height: 25.0,
                  child: GeneratedMenuWidget1(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.058666666666666666;

                    final double height =
                        constraints.maxHeight * 0.031484257871064465;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.08266666666666667,
                          y: constraints.maxHeight * 0.3733133433283358,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroupWidget(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 31.0,
                  top: 374.0,
                  right: null,
                  bottom: null,
                  width: 22.0,
                  height: 21.0,
                  child: GeneratedEllipse1Widget(),
                ),
                Positioned(
                  left: 31.0,
                  top: 500.0,
                  right: null,
                  bottom: null,
                  width: 22.0,
                  height: 21.0,
                  child: GeneratedEllipse5Widget(),
                ),
                Positioned(
                  left: 177.0,
                  top: 315.0,
                  right: null,
                  bottom: null,
                  width: 22.0,
                  height: 21.0,
                  child: GeneratedMinuslogoWidget(),
                ),
                Positioned(
                  left: 177.0,
                  top: 431.0,
                  right: null,
                  bottom: null,
                  width: 22.0,
                  height: 21.0,
                  child: GeneratedMinuslogoWidget1(),
                ),
                Positioned(
                  left: 178.0,
                  top: 560.0,
                  right: null,
                  bottom: null,
                  width: 22.0,
                  height: 21.0,
                  child: GeneratedMinuslogoWidget2(),
                ),
                Positioned(
                  left: 178.0,
                  top: 247.0,
                  right: null,
                  bottom: null,
                  width: 150.0,
                  height: 20.0,
                  child: GeneratedNotebookRollerCanteqWidget(),
                ),
                Positioned(
                  left: 178.0,
                  top: 372.0,
                  right: null,
                  bottom: null,
                  width: 114.0,
                  height: 20.0,
                  child: GeneratedPensil1set7pcsWidget(),
                ),
                Positioned(
                  left: 178.0,
                  top: 497.0,
                  right: null,
                  bottom: null,
                  width: 146.0,
                  height: 20.0,
                  child: GeneratedNotebookRollerBinderWidget(),
                ),
                Positioned(
                  left: 178.0,
                  top: 279.0,
                  right: null,
                  bottom: null,
                  width: 63.0,
                  height: 20.0,
                  child: GeneratedRp16000Widget(),
                ),
                Positioned(
                  left: 178.0,
                  top: 398.0,
                  right: null,
                  bottom: null,
                  width: 62.0,
                  height: 20.0,
                  child: GeneratedRp13000Widget(),
                ),
                Positioned(
                  left: 178.0,
                  top: 524.0,
                  right: null,
                  bottom: null,
                  width: 63.0,
                  height: 20.0,
                  child: GeneratedRp19000Widget(),
                ),
                Positioned(
                  left: 231.0,
                  top: 428.0,
                  right: null,
                  bottom: null,
                  width: 25.0,
                  height: 25.0,
                  child: GeneratedEOS_ADD_CIRCLE_OUTLINEDWidget(),
                ),
                Positioned(
                  left: 231.0,
                  top: 558.0,
                  right: null,
                  bottom: null,
                  width: 25.0,
                  height: 25.0,
                  child: GeneratedEOS_ADD_CIRCLE_OUTLINEDWidget1(),
                ),
                Positioned(
                  left: 213.0,
                  top: 315.0,
                  right: null,
                  bottom: null,
                  width: 11.0,
                  height: 26.0,
                  child: Generated1Widget(),
                ),
                Positioned(
                  left: 211.0,
                  top: 431.0,
                  right: null,
                  bottom: null,
                  width: 15.0,
                  height: 26.0,
                  child: Generated0Widget(),
                ),
                Positioned(
                  left: 211.0,
                  top: 559.0,
                  right: null,
                  bottom: null,
                  width: 15.0,
                  height: 26.0,
                  child: Generated0Widget1(),
                ),
                Positioned(
                  left: 0.0,
                  top: 614.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 53.0,
                  child: GeneratedRectangle201Widget(),
                ),
                Positioned(
                  left: 301.0,
                  top: 313.0,
                  right: null,
                  bottom: null,
                  width: 25.0,
                  height: 25.0,
                  child: GeneratedDeleteWidget(),
                ),
                Positioned(
                  left: 301.0,
                  top: 427.0,
                  right: null,
                  bottom: null,
                  width: 25.0,
                  height: 25.0,
                  child: GeneratedDeleteWidget1(),
                ),
                Positioned(
                  left: 301.0,
                  top: 557.0,
                  right: null,
                  bottom: null,
                  width: 25.0,
                  height: 25.0,
                  child: GeneratedDeleteWidget2(),
                ),
                Positioned(
                  left: 32.0,
                  top: 630.0,
                  right: null,
                  bottom: null,
                  width: 45.0,
                  height: 23.0,
                  child: GeneratedTotalWidget(),
                ),
                Positioned(
                  left: 72.0,
                  top: 627.0,
                  right: null,
                  bottom: null,
                  width: 97.0,
                  height: 26.0,
                  child: Generated16000Widget(),
                ),
                Positioned(
                  left: 221.0,
                  top: 623.0,
                  right: null,
                  bottom: null,
                  width: 105.0,
                  height: 35.0,
                  child: GeneratedButtonCheckoutWidget(),
                ),
                Positioned(
                  left: 230.0,
                  top: 312.0,
                  right: null,
                  bottom: null,
                  width: 25.0,
                  height: 25.0,
                  child: GeneratedEOS_ADD_CIRCLE_OUTLINEDWidget2(),
                )
              ]),
        ),
      ),
    ));
  }
}
