import 'package:flutter/material.dart';

/* UndefinedNode TTL
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTTLWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
